- README.md
- index.js
- package.json
- test/test.js
Need this to access headers on the original response. This expands on #12 by fixing and expanding unit tests and updating the readme. Version bump to `0.4.0` since #12 introduced a backwards incompatible signature change on the intercept callback.
> Intercept with original response from target

- index.js
Hi! 
I think is useful to have other request params when handling the request in decorateRequest function. In my specific case, I need the params of the url. Even may be good to pass the full req object (and delete it later) to have all the info available. ¿What do you think?
Many thanks for the project! 
BR
> Added request params to decorate request

- index.js
- test/test.js
Fixes #13.
Beware this always casts to string. Before `port` could have been either number or string type depending on whether it was parsed or defaulted.
> Fix: runtime error when there is both a port and a trailing slash

- index.js
Proposing the addition of this option, so that the host header that the upstream server gets is the same that the one the client originally requested.
This is more like the behavior that nginx provides by default for proxy_pass.
Thanks!
> Add preserveHostHdr option to act more like a reverse proxy

- index.js
- package.json
- test/test.js
Hi @villadora 
I'm using another library that consumes the `req` in order to validate that the right JSON values have been sent. After tracing it down I found that the proxy was hanging because the `req` was already consumed so no `end` events were being fired (maybe similar to #32) 
Since others might be using a middleware (such as `body-parser` or `swagger-framework`) which pre-process the `req` and put it in `req.body` if the proxy can check for `req.body` and use that if its defined, instead of always consuming the `req` stream, then the proxy can be used with other libraries that pre-decorate the body too.
What do you think?
-------
```
Before:
test proxy middleware compatibility
21 passing (11s)
1 failing
1) http-proxy test proxy middleware compatibility should use req.body if …
```
> using req.body if it has been pre-parsed

- index.js
This stops `express-http-proxy` from preserving the response's
`Transfer-Encoding` header.
Without this, when `express-http-proxy` tries to proxy a response with
`Transfer-Encoding: chunked` set, the response is de-chunked by waiting
on all the chunks and joining them, indeed, a `Content-Length` header is
computed and set if intercepting. But trying to send a response with
both `Content-Length` and `Transfer-Encoding: chunked` fails with a
`Parse error`, because it doesn't make sense.
Thus, we explicitly skip copying over `Transfer-Encoding`.
(For example, Puma with Rails 5 always sends replies that way.)
> Don't copy the response Transfer-Encoding header

- index.js
See commit comments for the reasoning behind this. I've passed it in as the 2nd argument to avoid breaking existing implementation.
> Pass original express 'req' object to decorateRequest

- index.js
- test/test.js
Sometime it's useful to get access to request session object in `decorateRequest` function, for instance using [express-session](https://github.com/expressjs/session) to manage the session.
To activate it just add `preserveReqSession` option and set it to `true`.
Example usage here: https://github.com/enricostano/proxy/blob/master/server.js#L28
Would be nice to have a more generic solution, for instance mapping `req` custom objects passed through. I'll further investigate about this but for now this solve the issue.
> Add preserveReqSession option

- index.js
- package.json
This changes the meaning of the proxy(`host`, ...) param slightly..
* a protocol is now required (url.parse needs it), thus https detection depends solely on the protocol
* port 443 no longer implies https
* an Error is `next`ed otherwise
* ipv6 addresses with port are now supported ([::1]:1234 would fail to split before)
Also removed unused `type-is`, and added `lodash.iserror`
> Use url.parse to parse the given host - IP6 support

- README.md
- index.js
- test/test.js
This is needed if you want to be able to send data using multipart/form-data. Otherwise data are altered since the proxy assume an utf-8 encoding.
> Preserve body encoding

- index.js
If proxy client request is aborted, proxied request now is aborted too and server stops processing the request.
> Manage aborted connection

- index.js
- test/intercept.js
Issue was we were not consistent with applying encoding; in this case we were making a request without specifying an encoding, then automatically decoding it as utf-8.
> Fixes Can't intercept html in response body

- index.js
- test/forwardPath.js
This is part of the API and was broken with 7d6e4f8 see https://github.com/villadora/express-http-proxy/commit/7d6e4f8384ed1de438de92dc92b636c861e934c2#diff-168726dbe96b3ce427e7fedce31bb0bcL32
> Add response when calling `forwardPath`.

- README.md
This option can only be found in the code or in issue #27 but is
quite important to know when using the proxy for large request.
> Add documentation for options.limit.

- README.md
from
```js
app.use('proxy(getHost, {
memoizeHost: false
}
)
```
to
```js
app.use(proxy(getHost, {
memoizeHost: false
}))
```
> Fixed typo readme

- README.md
- app/steps/decorateProxyReqOpts.js
- app/steps/prepareProxyReq.js
- index.js
- lib/decorateUserRes.js
- lib/sendProxyRequest.js
- lib/sendUserRes.js
- test/intercept.js
- test/middlewareCompatibility.js
- test/support/proxyTarget.js
…ts sequential to avoid issues with passed-by-reference 'container'.
Extract prepareProxyReq as a separate module
> Make decorate request steps sequential

- app/steps/buildProxyReq.js
- test/bodyEncoding.js
The promise that was being returned from the `buildProxyReq` was not handling a rejection if the body parsing failed - for example if the body size exceeded the configured limit. This caused node to throw an unhandled rejection error and crash the request.
By removing the redundant `new Promise` wrapper from around the `Promise.all` call the inner promise will correctly propogate its rejection, and allow it to be caught at https://github.com/villadora/express-http-proxy/blob/11737ce02348fd8077a0ee8db6b14f7a25a0cdb0/index.js#L56
> Prevent unhandled promise rejection error when body size exceeds limit

- app/steps/decorateUserRes.js
Add test, so unzipping is called only when data are present
> Fix crash when gzip indicated and body is empty

- app/steps/decorateProxyReqOpts.js
When debugging is disabled, calling `debug('Whatever', JSON.stringify(data))` will cause the data to be stringified, even if debugging is disabled. The proper usage of the `debug` package requires to use `%o` or `%O` to pretty-print objects.
> [#391] Proper debugging of objects

- lib/resolveOptions.js
- test/middlewareCompatibility.js
- test/traceDebugging.js
- test/verbs.js
#393 made it so that only one test that is ever run. If you check the last several travis logs since that PR you will see they never ran any of the other tests.
https://travis-ci.org/villadora/express-http-proxy/jobs/455092315
This PR fixes this
couple notes, in addition to removing the `.only` from the `describe` which allows the rest of the test suite to run, I discovered that http://httpbin.org/get changed the URL that is returned to have `https` so there was a test that was previously being skipped that was failing so I updated that.
I also noticed that the tests threw a deprecation notice since they were using `intercept` instead of `userResDecorator`. I changed the invocation and updated the deprecation notice so that it returns the prints the correct function name.
> fix broken test suite from #393

- README.md
I spent 2 days to find my issue. It was very hard to find the problem, but in some case, the body-parser change the body POST, and thn this body post is not sent to the target correctly. Hope it helps
> Add important note about 'body-parser'

- app/steps/buildProxyReq.js
- app/steps/maybeSkipToNextHandler.js
- index.js
- lib/requestOptions.js
- package.json
- test/defineMultipleProxyHandlers.js
- test/maybeSkipToNextHandler.js
The issue here was that a dependency, `getRawBody` mutates the req object in a way that makes calling `getRawBody` not idempotent. Most of the solve here was stashing the results of the first call of getRawBody so we can skip this for the second pass. Added new tests demonstrating this capability.
> [501] Repairs => Can't use proxy() twice in Express middleware stack.

- README.md
- app/steps/sendProxyRequest.js
- lib/requestOptions.js
- test/getBody.js
- test/postBody.js
Our exact use-case is a bit special:
1. We have a NestJS application, and we still want to use our NestJS guards before proxying
2. Our endpoint needs to set `{ strict: false }` for the JSON body parser, because our proxied endpoint can take in non-objects as input
3. We don't want to parse the incoming request at all. The exact use case we're thinking of is JSON data with big ints that would get rounded if it went through standard `body-parser` functions
So to implement this, we extracted out the raw body before `body-parser` can touch it, then for our proxy, we did
```
proxy('...', {
proxyReqBodyDecorator: () => rawBody,
})
```
to completely ignore the body that was parsed by `body-parser`/`express-http-proxy` and manually set the body back to the raw body we got.
But in our testing, we …
> Supporting proxy after request body has been read

- test/bodyEncoding.js
- test/catchingErrors.js
- test/constants.js
- test/cookies.js
- test/decorateUserResHeaders.js
- test/defineMultipleProxyHandlers.js
- test/getBody.js
- test/headers.js
- test/host.js
- test/https.js
- test/maybeSkipToNextHandler.js
- test/params.js
- test/path.js
- test/postBody.js
- test/preserveHostHdr.js
- test/proxyReqPathResolver.js
- test/setsContentLength.js
- test/streaming.js
- test/urlParsing.js
- test/userResDecorator.js
This PR extracts test timeouts to DRY them up, and shortens a couple of unnecessarily long timeouts.
> Clean up timeouts and shorten some test timeouts.

- app/steps/sendProxyRequest.js
Same PR as [this](https://github.com/http-party/node-http-proxy/pull/1559), for the same reason
Credit to @Jimbly
> implement memory leak fix from http-proxy
